### ISSUE TITLE
1.19.2 version please???

### ISSUE THREAD

**Issue by kuronekony4n** [IoeCmcomc/command_extractor#1]
I need this really bad, for fabric 1.19.2

**Comment by IoeCmcomc** [comment]
Please be patient. I will do that at the weekend.

**Comment by IoeCmcomc** [comment]
@kuronekony4n Fabric 1.19.2 version is now available: https://modrinth.com/mod/command_extractor/version/SyNgT3k6

**Comment by kuronekony4n** [comment]
what is this tool meant for?

**Comment by IoeCmcomc** [comment]
@kuronekony4n This is useful for anyone **using or developing data pack and command-related tools and want to add non-vanilla commands supports in those tools**. As far as I know only [MCDatapacker](https://github.com/IoeCmcomc/MCDatapacker) supports custom commands; other tools such as beet, Spyglass and mcfunction-debugger may have custom commands support in the future.
